postgresql:
    auth:
        username: lights
        password: lights
        database: lightsdb

    primary:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    readReplicas:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    volumePermissions:
        enabled: false
        securityContext:
            runAsUser: "auto"

deployment:
    image: quay.io/wpernath/light-control
    version: latest
    replicas: 1
    includeHealthChecks: false

config:
    greeting: 'Hello from chart with subchart'

