apiVersion: v1
kind: Ingress
metadata:
  labels:
    app: person-service
    app.kubernetes.io/part-of: {{ .Release.Name }}-chart
  name: {{ .Release.Name }}-route
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ .Release.Name }}-service
    weight: 100
  wildcardPolicy: None
