apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: light-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: light-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/dev
    repoURL: https://github.com/wpernath/light-control-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: light-stage
  namespace: openshift-gitops
spec:
  destination:
    namespace: light-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/stage
    repoURL: https://github.com/wpernath/light-control-config.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - PruneLast=true

